#
# this a cofiguration templated provided by the software provider
# it contain a default configuration for product P1
# and markers for paraneters required to be set in an installation
# specific manner:
#

#
# The dnsName is the DNS name to be used for the installed service
# It must be set specific for a dedicated installation.
#
dnsName: service.installation1.acme.org

#
# replicas specifies the number of pods to be deployed 
# for the installed service.
#
<<<<<<< HEAD
replicas: 1 # this is the delivery default

#
# color is used as background color for your UI
#
color: "#f0f000"

=======
replicas: 10
>>>>>>> origin/main
