#
# this a cofiguration templated provided by the software provider
# it contain a default configuration for product P2
# and markers for parameters required to be set in an installation
# specific manner:
#

#
# The dnsName is the DNS name to be used for the installed service
# It must be set specific for a dedicated installation.
#
dnsName: <REQUIRED>

#
# replicals specified the numer of pods to be deployed 
# for the installed service.
#
replicas: 1 # this is the delivery default

#
# uses described the instances of used services provided by other 
# installations
#
uses:
  #
  # P2 requires an instance of P1 to work
  p1: <REQUIRED>
